/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBox: typeof import('./src/components/ai/ChatBox.vue')['default']
    ChatHome: typeof import('./src/components/ai/ChatHome.vue')['default']
    ChatInput: typeof import('./src/components/ai/ChatInput.vue')['default']
    CollapseIcon: typeof import('@/components/icon/CollapseIcon.vue')['default']
    CourseCard: typeof import('./src/components/student/CourseCard.vue')['default']
    ExpandIcon: typeof import('@/components/icon/ExpandIcon.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/form/ForgotPasswordForm.vue')['default']
    GdLoadingText: typeof import('./src/components/common/GdLoadingText.vue')['default']
    GdStack: typeof import('./src/components/common/GdStack.vue')['default']
    GdTag: typeof import('./src/components/common/GdTag.vue')['default']
    HistoryCard: typeof import('./src/components/ai/HistoryCard.vue')['default']
    LoadingState: typeof import('./src/components/common/LoadingState.vue')['default']
    LoginForm: typeof import('./src/components/form/LoginForm.vue')['default']
    MarkdBox: typeof import('./src/components/common/MarkdBox.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MyLogo: typeof import('./src/components/common/MyLogo.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    QuestionForm: typeof import('./src/components/teacher/QuestionForm.vue')['default']
    QuestionList: typeof import('./src/components/teacher/QuestionList.vue')['default']
    RegisterForm: typeof import('./src/components/form/RegisterForm.vue')['default']
    RichTextEditor: typeof import('./src/components/common/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarMenu: typeof import('@/components/ai/SideBarMenu.vue')['default']
    StudentList: typeof import('./src/components/common/StudentList.vue')['default']
    StudentSideBarMenu: typeof import('./src/components/student/StudentSideBarMenu.vue')['default']
    StudentStatsCharts: typeof import('./src/components/charts/StudentStatsCharts.vue')['default']
    TeacherSideBarMenu: typeof import('./src/components/teacher/TeacherSideBarMenu.vue')['default']
    TeacherStatsCharts: typeof import('./src/components/teacher/TeacherStatsCharts.vue')['default']
    TitleBar: typeof import('./src/components/common/TitleBar.vue')['default']
  }
}
