/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBox: typeof import('./../components/AI/ChatBox.vue')['default']
    ChatHome: typeof import('./../components/AI/ChatHome.vue')['default']
    ChatInput: typeof import('./../components/AI/ChatInput.vue')['default']
    CourseCard: typeof import('./../components/student/CourseCard.vue')['default']
    HistoryCard: typeof import('./../components/AI/HistoryCard.vue')['default']
    LoadingState: typeof import('./../components/common/LoadingState.vue')['default']
    LoginForm: typeof import('./../components/form/LoginForm.vue')['default']
    MarkdBox: typeof import('./../components/common/MarkdBox.vue')['default']
    MyLogo: typeof import('./../components/common/MyLogo.vue')['default']
    RegisterForm: typeof import('./../components/form/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderBarMenu: typeof import('./../components/AI/SiderBarMenu.vue')['default']
    StudentSiderBarMenu: typeof import('./../components/student/StudentSiderBarMenu.vue')['default']
    StudentStatsCharts: typeof import('./../components/charts/StudentStatsCharts.vue')['default']
    TeacherSiderBarMenu: typeof import('./../components/teacher/TeacherSiderBarMenu.vue')['default']
    TitleBar: typeof import('./../components/common/TitleBar.vue')['default']
  }
}
